services:

  app:
    build:
      context: ./app     
    container_name: app
    networks:
      - proxy_chain

  networks:
    proxy_chain:
      driver: bridge
      ipam:
        config:
          - subnet: 172.30.0.0/24