services:

  app:
    build:
      context: ./app     
    container_name: app
    networks:
      - proxy_chain

  nginx1:
    build:
      context: ./nginx
    container_name: nginx1
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx1.conf:/etc/nginx/nginx.conf
    networks:
      - proxy_chain

networks:
  proxy_chain:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24